version: "3"

services:
  app:
    build:
      context: app
      dockerfile: .docker/Dockerfile
  nginx:
    restart: always
    build: 
      context: nginx
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
      - "443:443"
