name: Build and deploy

on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-20.04
    environment: Production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clean install app
        run: npm --prefix app ci

      - name: Install angular cli
        run: npm i -g @angular/cli@12

      - name: npm build app
        run: npm --prefix app run build:ssr

      - name: Deploy dist to Canada
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.CANADA_SERVER_USER }}
          server: ${{ secrets.CANADA_SERVER_IP }}
          ssh_private_key: ${{ secrets.CANADA_SERVER }} 
          local_path: ./app/dist
          remote_path: ./server/app/
          args: '-o ConnectTimeout=5'

      - name: Deploy app to Canada
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.CANADA_SERVER_USER }}
          server: ${{ secrets.CANADA_SERVER_IP }}
          ssh_private_key: ${{ secrets.CANADA_SERVER }} 
          local_path: ./app/.docker
          remote_path: ./server/app/
          args: '-o ConnectTimeout=5'

      - name: Deploy nginx to Canada
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.CANADA_SERVER_USER }}
          server: ${{ secrets.CANADA_SERVER_IP }}
          ssh_private_key: ${{ secrets.CANADA_SERVER }} 
          local_path: ./nginx
          remote_path: ./server
          args: '-o ConnectTimeout=5'

      - name: Deploy scripts to Canada
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.CANADA_SERVER_USER }}
          server: ${{ secrets.CANADA_SERVER_IP }}
          ssh_private_key: ${{ secrets.CANADA_SERVER }} 
          local_path: ./deployment/deploy.sh
          remote_path: ./server
          args: '-o ConnectTimeout=5'
      
      - name: Deploy compose to Canada
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.CANADA_SERVER_USER }}
          server: ${{ secrets.CANADA_SERVER_IP }}
          ssh_private_key: ${{ secrets.CANADA_SERVER }} 
          local_path: ./deployment/docker-compose.yml
          remote_path: ./server
          args: '-o ConnectTimeout=5'
      
      - name: Deploy to Canada
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CANADA_SERVER_IP }}
          username: ${{ secrets.CANADA_SERVER_USER }}
          key: ${{ secrets.CANADA_SERVER }} 
          port: 22
          script: |
            cd server
            bash ./deploy.sh
