# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ deploy-production ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clean install app
        run: npm --prefix app ci

      - name: Install angular cli
        run: npm i -g @angular/cli@12

      - name: npm build app
        run: |
          npm --prefix app run build 
          ls -l
          ls -l dist
          ls -l app/
